# Generated by Django 6.0.4 on 2026-05-01 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_birth_date_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=40)),
                ('zip_code', models.CharField(max_length=9)),
                ('street', models.CharField(max_length=120)),
                ('number', models.CharField(max_length=20)),
                ('complement', models.CharField(blank=True, default='', max_length=80)),
                ('neighborhood', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=2)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_favorite', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_favorite', True)), fields=('user',), name='unique_favorite_address_per_user')],
            },
        ),
    ]
