# Generated by Django 6.0.4 on 2026-05-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
